! TOUCHSTONE file generated by CST MICROWAVE STUDIO
! Date and time: Wed Jan 22 20:12:45 2025
! Project name: NUEVA_TRANSICION_CORTO.cst
! Parameters = {DespTor=4.318; H=17; Hcono=2.59394; Hstep1=13.4144; Hstep2=6.31893; Hstep3=0; Htuerca=0.1; L=55; Lback=11; Ldielectrico=9.525; Lstep1=12.9914; Lstep2=10.8318; Lstep3=9.99957; Ltor=4; Nsegments=0; Ragujero=1.4615; Rcono1=4.39874; Rcono2=2.78582; Rext=2.055; Rint=0.635; Rtor=1.275; Rtuerca=2.451; Target=-30; W=34; lopt1=0.632257; lopt2=6.83182; lopt3=5.99957; rrcono2=2.78582; thickness=2; topthickness=3}
! Header version: 2018
! Port assignment regex: !\s*Touchstone port\s*([0-9]+)\s*=\s*(CST MWS port|CST DS port)\s*([0-9]+|Zmin|Zmax)\s*\(\"(.*)\"\)(\s*mode\s*([0-9]+))?.*
! Touchstone port assignment:
! Touchstone port 1 = CST MWS port 1 ("")
! Touchstone port 2 = CST MWS port 2 ("")
[Version] 2.0
# GHz Y DB R 1
[Number of Ports] 2
[Two-Port Data Order] 21_12
[Number of Frequencies] 5002



